//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuserExcelTransformer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuserExcelTransformer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auser Excel Transformer.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File CSV:.
        /// </summary>
        internal static string CSVFileLabel {
            get {
                return ResourceManager.GetString("CSVFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarica.
        /// </summary>
        internal static string DownloadButton {
            get {
                return ResourceManager.GetString("DownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il file CSV contiene dati non validi o è corrotto..
        /// </summary>
        internal static string ErrorCSVMalformed {
            get {
                return ResourceManager.GetString("ErrorCSVMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile leggere il file CSV. Verificare che il file esista e sia accessibile..
        /// </summary>
        internal static string ErrorCSVFileRead {
            get {
                return ResourceManager.GetString("ErrorCSVFileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il file CSV non contiene le colonne richieste: {0}.
        /// </summary>
        internal static string ErrorCSVMissingColumns {
            get {
                return ResourceManager.GetString("ErrorCSVMissingColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante la trasformazione dei dati..
        /// </summary>
        internal static string ErrorDataTransformation {
            get {
                return ResourceManager.GetString("ErrorDataTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nell'analisi delle date nell'intestazione..
        /// </summary>
        internal static string ErrorDateParsing {
            get {
                return ResourceManager.GetString("ErrorDateParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile leggere il file Excel. Verificare che il file esista e sia accessibile..
        /// </summary>
        internal static string ErrorExcelFileRead {
            get {
                return ResourceManager.GetString("ErrorExcelFileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile salvare il file. Verificare i permessi di scrittura..
        /// </summary>
        internal static string ErrorFileSave {
            get {
                return ResourceManager.GetString("ErrorFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il foglio 'fissi' non è stato trovato nel file Excel..
        /// </summary>
        internal static string ErrorFissiSheetNotFound {
            get {
                return ResourceManager.GetString("ErrorFissiSheetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore: {0}.
        /// </summary>
        internal static string ErrorGeneral {
            get {
                return ResourceManager.GetString("ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile analizzare l'intestazione del foglio precedente. Verificare il formato..
        /// </summary>
        internal static string ErrorHeaderParsing {
            get {
                return ResourceManager.GetString("ErrorHeaderParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Excel:.
        /// </summary>
        internal static string ExcelFileLabel {
            get {
                return ResourceManager.GetString("ExcelFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elabora.
        /// </summary>
        internal static string ProcessButton {
            get {
                return ResourceManager.GetString("ProcessButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva file Excel.
        /// </summary>
        internal static string SaveFileDialogTitle {
            get {
                return ResourceManager.GetString("SaveFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona file CSV.
        /// </summary>
        internal static string SelectCSVButton {
            get {
                return ResourceManager.GetString("SelectCSVButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona file CSV.
        /// </summary>
        internal static string SelectCSVDialogTitle {
            get {
                return ResourceManager.GetString("SelectCSVDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona file Excel.
        /// </summary>
        internal static string SelectExcelButton {
            get {
                return ResourceManager.GetString("SelectExcelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona file Excel.
        /// </summary>
        internal static string SelectExcelDialogTitle {
            get {
                return ResourceManager.GetString("SelectExcelDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File salvato con successo!.
        /// </summary>
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elaborazione completata con successo! Ora puoi scaricare il file..
        /// </summary>
        internal static string ProcessingComplete {
            get {
                return ResourceManager.GetString("ProcessingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il foglio 'assistiti' non è stato trovato nel file Excel..
        /// </summary>
        internal static string AssistitiSheetNotFound {
            get {
                return ResourceManager.GetString("AssistitiSheetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il foglio di riferimento '{0}' ha una struttura non valida..
        /// </summary>
        internal static string ReferenceSheetMalformed {
            get {
                return ResourceManager.GetString("ReferenceSheetMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonna '{0}' non trovata nel foglio di riferimento..
        /// </summary>
        internal static string ColumnNotFoundInReference {
            get {
                return ResourceManager.GetString("ColumnNotFoundInReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato data non valido nella riga {0}..
        /// </summary>
        internal static string InvalidDateFormat {
            get {
                return ResourceManager.GetString("InvalidDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato ora non valido nella riga {0}..
        /// </summary>
        internal static string InvalidTimeFormat {
            get {
                return ResourceManager.GetString("InvalidTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il file dei volontari non è stato trovato..
        /// </summary>
        internal static string ErrorVolunteerFileNotFound {
            get {
                return ResourceManager.GetString("ErrorVolunteerFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il file dei volontari contiene dati non validi o è corrotto..
        /// </summary>
        internal static string ErrorInvalidVolunteerFile {
            get {
                return ResourceManager.GetString("ErrorInvalidVolunteerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il cognome non può essere vuoto..
        /// </summary>
        internal static string ErrorEmptySurname {
            get {
                return ResourceManager.GetString("ErrorEmptySurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L'indirizzo email non è valido..
        /// </summary>
        internal static string ErrorInvalidEmail {
            get {
                return ResourceManager.GetString("ErrorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler eliminare tutti i contatti dei volontari? Questa operazione non può essere annullata..
        /// </summary>
        internal static string ConfirmDeleteAllVolunteers {
            get {
                return ResourceManager.GetString("ConfirmDeleteAllVolunteers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi Volontari.
        /// </summary>
        internal static string AddVolunteersButton {
            get {
                return ResourceManager.GetString("AddVolunteersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi Contatto.
        /// </summary>
        internal static string AddContactButton {
            get {
                return ResourceManager.GetString("AddContactButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina Tutti.
        /// </summary>
        internal static string DeleteAllButton {
            get {
                return ResourceManager.GetString("DeleteAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invia Email.
        /// </summary>
        internal static string SendEmailsButton {
            get {
                return ResourceManager.GetString("SendEmailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognome.
        /// </summary>
        internal static string VolunteerListColumnSurname {
            get {
                return ResourceManager.GetString("VolunteerListColumnSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string VolunteerListColumnEmail {
            get {
                return ResourceManager.GetString("VolunteerListColumnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contatti Volontari.
        /// </summary>
        internal static string VolunteerContactsGroupTitle {
            get {
                return ResourceManager.GetString("VolunteerContactsGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La colonna 'Volontario' non è stata trovata nel foglio selezionato..
        /// </summary>
        internal static string ErrorNoVolontarioColumn {
            get {
                return ResourceManager.GetString("ErrorNoVolontarioColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile connettersi al server Gmail SMTP. Verificare le credenziali..
        /// </summary>
        internal static string ErrorGmailConnection {
            get {
                return ResourceManager.GetString("ErrorGmailConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il file Excel non contiene fogli..
        /// </summary>
        internal static string ErrorEmptyExcelFile {
            get {
                return ResourceManager.GetString("ErrorEmptyExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il file di configurazione è corrotto. Utilizzando configurazione vuota..
        /// </summary>
        internal static string ErrorConfigCorrupted {
            get {
                return ResourceManager.GetString("ErrorConfigCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servizi Assegnati - Settimana {0}.
        /// </summary>
        internal static string EmailSubjectTemplate {
            get {
                return ResourceManager.GetString("EmailSubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gentile {0},.
        /// </summary>
        internal static string EmailGreetingTemplate {
            get {
                return ResourceManager.GetString("EmailGreetingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecco i servizi assegnati per questa settimana:.
        /// </summary>
        internal static string EmailBodyIntro {
            get {
                return ResourceManager.GetString("EmailBodyIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---.
        /// </summary>
        internal static string EmailBodyRowSeparator {
            get {
                return ResourceManager.GetString("EmailBodyRowSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grazie per la tua disponibilità..
        /// </summary>
        internal static string EmailBodyClosing {
            get {
                return ResourceManager.GetString("EmailBodyClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invio email in corso....
        /// </summary>
        internal static string EmailSendingProgress {
            get {
                return ResourceManager.GetString("EmailSendingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invio completato. Email inviate con successo: {0}. Email non inviate: {1}..
        /// </summary>
        internal static string EmailSummaryTemplate {
            get {
                return ResourceManager.GetString("EmailSummaryTemplate", resourceCulture);
            }
        }
    }
}
